### ISSUE TITLE
attempt to index field 'language' (a nil Value)

### ISSUE THREAD

**Issue by Dantill** [nitrous24/Lua#29]
Trying to get azureSets to work for my blu but keep getting this error

**Comment by nitrous24** [comment]
Do me a favor and post a copy of your azuresets/data/settings.xml here. As i don't get that error even if i change the language

**Comment by Dantill** [comment]
<?xml version="1.1" ?>
<settings>
    <global>
        <assimilation>5</assimilation>
        <language>english</language>
        <spellsets>
            <default />
            <warsub>
                <slot01>Magic Fruit</slot01>
                <slot02>Battery Charge</slot02>
                <slot03>Occultation</slot03>
                <slot04>Amorphic Spikes</slot04>
                <slot05>Head Butt</slot05>
                <slot06>Actinic Burst</slot06>
                <slot07>Winds of Promy.</slot07>
                <slot08>Empty Thrash</slot08>
                <slot09>Heavy Strike</slot09>
                <slot10>Acrid Stream</slot10>
                <slot11>Demoralizing Roar</slot11>
                <slot12>Quad. Continuum</slot12>
                <slot13>Delta Thrust</slot13>
                <slot14>Barbed Crescent</slot14>
                <slot15>Blazing Bound</slot15>
                <slot16>Animating Wail</slot16>
                <slot17>Mortal Ray</slot17>
                <slot18>Dream Flower</slot18>
            </warsub>
        </spellsets>
    </global>
</settings>

**Comment by Dantill** [comment]
the error I am getting is to do with the azuresets.lua code says line 164 is the problem

**Comment by nitrous24** [comment]
I can't duplicatet hat error. Have you reloaded the launcher and reloaded the addon lately? could be an issue from one of the libraries that has been fixed

**Comment by Dantill** [comment]
Ok ill try that and get back to you

Thanks

**Comment by Dantill** [comment]
deleted and reinstalled. works fine now. no idea what was wrong

thanks for the help though dude appreciate it

**Comment by nitrous24** [comment]
np and have fun with the addon
