### ISSUE TITLE
Crashing on shutting down

### ISSUE THREAD

**Issue by geekgirl101** [nitrous24/Lua#33]
When shutting down FFXI the FFXI window goes black and doesn't shut down properly, I have to kill it via task manager.  Since no error is produced there is no crash log.  The addons that are doing this are azureSets, ohShi and Staggertrack, none of the others I use cause the game to lock up on shutting down.

**Comment by nitrous24** [comment]
mine crashes/locks up on shutdown as well even when i'm not using addons. So it's not really something i can debug ><
