### ISSUE TITLE
OhShi sometimes does not load correctly when dualboxing

### ISSUE THREAD

**Issue by quedari** [nitrous24/Lua#39]
First instance loads correctly. Log in on second instance, and once it starts loading up all the plugins and addons, sometimes OhShi will cause the entire screen to dim like background of the box is covering the whole screen, and the "OhShi Initialized" box won't pop up. Usually unloading OhShi on both chars and reloading it fixes it, but sometimes i have to do this multiple times for it to work.

**Comment by nitrous24** [comment]
the whole screen thing is a bug in the hook. i assume what happens is when it does that the text is off the screen which is why you don't see it.
