### ISSUE TITLE
Autocontrol: Doesn't set frames/attachments

### ISSUE THREAD

**Issue by Sechs** [nitrous24/Lua#72]
It gives a message in the console BG "Attachment XXXX already set" and then doesn't correctly apply the whole saved set in the xml.

**Comment by nitrous24** [comment]
ermm.. i just tried this and it perfectly set it.. i think it's an issue with luacore. there's a new one it just has to be pushed live.. leaving this open lemme know if a new luacore fixes

**Comment by Sechs** [comment]
Logged in, downloaded a new luacore, works like a charm ;)
Must have been the luacore I downloaded this morning, pretty sure 2 days ago it was working perfectly.
