### ISSUE TITLE
Autocontrol: Error if no command given

### ISSUE THREAD

**Issue by Sechs** [nitrous24/Lua#73]
Small issue which doesn't create any negative consequence.
If you attempt to call Autocontrol without giving any specific command (for instance "//acon" and nothing else) it gives  lua error

autocontrol: Lua error (runtime) - .../path/autocontrol.lua:235: attempt to index a nil value

**Comment by nitrous24** [comment]
i believe i fixed this a while back if not feel free to reopen this or make another issue about it
