### ISSUE TITLE
AutoControl: Burden window doesn't read settings

### ISSUE THREAD

**Issue by Sechs** [nitrous24/Lua#74]
In spite of what you put in the xml the addon doesn't "read" those settings and always load the window at the default position of 0,0 with a font size of 12.

If you force a difference from in-game commands it works and it also gets correctly updated in the XML, but next time you load the addon it still doesn't read whatever it's inside the XML and loads with the defaults.

Also if you unload/reload the addon with the automaton already out the window doesn't get loaded. It will get loaded if you deactivate/activate though, but this doesn't seem to be working with Deus Ex Automata.

**Comment by nitrous24** [comment]
fixed
