### ISSUE TITLE
Equipset

### ISSUE THREAD

**Issue by MysteryAidan** [nitrous24/Lua#76]
Error when using //autocontrol equipset 

"autocontrol.lua:188: attempt to index field '?' (a nil value)

**Comment by nitrous24** [comment]
erm... do what now? i swear i just fixed this the other day have you updated?

**Comment by MysteryAidan** [comment]
Updated, but I haven't restarted the game client in a few days.

There was a LuaCore update just a bit ago, and it seems to be working now?

Happened shortly after I switched my subjob, so I'm not sure what's going on.  But it is definitely working now!

**Comment by MysteryAidan** [comment]
Okay, so it worked once.  After that one time, it completely stops and pops up with the error above.

**Comment by nitrous24** [comment]
ok i'm gonna need to see your settings. as mine works fine

**Comment by MysteryAidan** [comment]
http://pastebin.com/bFGWAssU

Not sure what's going on.  I don't even think I've changed anything besides adding a few new attachments.

**Comment by nitrous24** [comment]
yea, mine works fine even with your settings. Make sure you have version 1.0 i just pushed an update  an hour or so ago.

**Comment by MysteryAidan** [comment]
I'll restart client, as I just updated via launcher ~10 minutes ago before I tried again and definitely on version 1.0.

Delve at the moment so it'll be a bit.  Thanks for the assistance though! =)

**Comment by nitrous24** [comment]
nah if you're on 1.0 you have everything i've changed lately.... i just don't get it.

**Comment by nitrous24** [comment]
maybe i'm missing something.. what command are you sending to do it? maybe i'm looking at the wrong thing.

**Comment by MysteryAidan** [comment]
in console: autocontrol equipset ranged

or in chat: //autocontrol equipset ranged

**Comment by MysteryAidan** [comment]
Like I said, worked fine for switching from ranged to healer set... then error when trying to do equipset again.

**Comment by nitrous24** [comment]
yea i've checked again on live windower and everything is fine. you may end up having to redownload it as i'm out of reasons it would be failing atm.

**Comment by MysteryAidan** [comment]
Will do that after restarting client if I'm still having issues.

I'll let you know probably tomorrow if it starts working!

**Comment by MysteryAidan** [comment]
Fresh download, and restarted client.

No change, except now it won't even let me change at all!

**Comment by MysteryAidan** [comment]
Hrmmmm messed with the settings a little bit.  Got rid of the meleerng hybrid because I never use it anyway.  Now all of a sudden it's working just fine?

Could it possibly be throwing errors now if you don't have an attachment in a set?  Because that's all I can think of.

It used to just say something like, "You don't have this attachment" and move on though.

**Comment by nitrous24** [comment]
this makes no sense >< it works fine on mine ><

**Comment by nitrous24** [comment]
perhaps. do you not have all attachments and/or are you trying to use one
you don't have

**Comment by MysteryAidan** [comment]
I think I'm missing one or two in the hybrid set. But I had all of the attachments in the set I was trying to equip. 

Works fine now though, I swapped back and forth 6 times to make sure it wouldn't throw an error. Thanks for the help, one of my favorite add one!

**Comment by nitrous24** [comment]
glad to have found the issue >.> though it shouldn't have mattered with the
other sets >< it only compares the one you're trying to equip and you're
current one.
