### ISSUE TITLE
After update in ffxi cor roll statues have stopped working.

### ISSUE THREAD

**Issue by itsintheboscage** [nitrous24/Lua#77]
No when I roll error messages appear and nothing else.

**Comment by itsintheboscage** [comment]
now*

**Comment by nitrous24** [comment]
I assume you mean for OhShi. I'll look into this tomorrow.

**Comment by itsintheboscage** [comment]
Okay. Thank you

**Comment by nitrous24** [comment]
Github went stupid and didn't post my last reply to this. I checked and had no issues with cor rolls. Try deleteing your ohshi folder and your libs folder and getting new ones for each.
