### ISSUE TITLE
Windower update? seems to have caused problems.

### ISSUE THREAD

**Issue by ffxiflyingsquirrel** [nitrous24/Lua#78]
"autocontrol: Lua error (runtime) - ... (x86)/windower4//addons/autocontrol.lua:188: attempt to index field '?' (a nil value)"

I keep receiving this message.  It randomly started happening last night, and I know there are alot of people having trouble with many windower add ons such as gearswap as well.  Any help would be great since I fulltime PUP and I got so used to autocontrol I can't play effectively without it! =(

**Comment by nitrous24** [comment]
Fixed. was a resources change i was unaware of. Should just be able to reopen launcher and get the new one.
