### ISSUE TITLE
OhShi: Lua error (runtime)

### ISSUE THREAD

**Issue by quedari** [nitrous24/Lua#79]
Every time I use light/dark arts or a stratagem on sch I get this error in the console:
OhShi: Lua error (runtime) - C:/Program Files/Windower4//addons/ohShi/ohShi.lua:213: attempt to index field '?' (a nil value)

**Comment by nitrous24** [comment]
I'm hoping i fixed this. I'm sorry it took me so long, for some reason i didn't get an email on this when you posted it. please feel free to reopen and comment if it's not fixed.

**Comment by quedari** [comment]
Got another one when I logged on just now.   ohShi.lua:53: attempt to call field 'spells' (a table value)
edit: I couldn't find a way to reopen, sorry :/

**Comment by nitrous24** [comment]
i think i fixed it this time. let me know if i didn't
